---
title: "Quality Control Report"
author: "Aina Montalban"
date: "1/28/2020"
output: 
  pdf_document:
    df_print: kable
geometry: margin=1in
fig_width: 4
fig_height: 4
params:
  data: shinyMethylSet1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Targets

```{r}
rgSet <- params$data
targets <- rgSet@phenotype
norm <- rgSet@norm
directory <- "~/Documents/methylation-shiny"
# source(paste0(directory, "/", "plotPCA.R"))
# source(paste0(directory, "/", "plotPropFailedProbes.R"))
```

```{r}
#head(targets[,c("Sample_Name", "Sample_Group", "Array", "Slide", "age", "sex", "status")], 10)
```

```{r}
colnames(rgSet@snps) <- targets$Sample_Name
heatmap.2(rgSet@snps, trace = "none",cexCol = 0.5 ,keysize=2,col=colorRampPalette(c("yellow","orange","red"))(100))
```

```{r}
 sampleColorsPCA <- function(){
      return(as.numeric(as.factor(targets[,match("Sample_Group",
                                                    colnames(targets))])))
    }
```



```{r}
pval_means <- colMeans(rgSet@detP)
df_pval_means <- as.data.frame(pval_means)
colnames(df_pval_means) <- "pvals"
ggplot(df_pval_means, aes(x=rownames(df_pval_means), y=pvals)) +
        geom_col(show.legend = FALSE, color="darkgrey") +
        theme_classic() + 
        scale_y_continuous(limits=c(0,0.08)) + 
        geom_hline(yintercept = 0.05, color="red") + 
        theme(axis.text.x = element_text(hjust = 1, angle=45)) +
        labs(y="P-values", x="")+
        geom_hline(yintercept = 0.01, color="green")
```


```{r cars}
par(mfrow=c(1,2))
minfi::densityPlot(rgSet@betaMatrix, sampGroups = targets$Sample_Group, main="Beta-values", legend = FALSE)
minfi::densityPlot(norm@mMatrix, sampGroups = targets$Sample_Group, main="M-values", xlab="M values", legend = FALSE)

```


```{r}
par(mfrow=c(1,2))
minfi::densityPlot(rgSet@mMatrix, sampGroups = targets$Sample_Group, main="M-values", xlab="M values", legend = FALSE)
minfi::densityPlot(norm@mMatrix, sampGroups = targets$Sample_Group, main="M-values", xlab="M values", legend = FALSE)
```


```{r}

xlab <- paste("PC 1", " scores", sep="")
ylab <- paste("PC 2", " scores", sep="")
xMin <- min(rgSet@pca$scores[,as.numeric(1)])
xMax <- max(rgSet@pca$scores[,as.numeric(2)])
xRange <- xMax - xMin
xlim <- c(xMin-0.05*xRange, xMax+0.20*xRange)
par(mfrow=c(1,2))
plot(rgSet@pca$scores[,1], rgSet@pca$scores[,2],
         col = sampleColorsPCA(), pch = 19, cex = 2, xlab = xlab,
         ylab = ylab, xlim = xlim,
         main = "Beta-values (PCA)",
         cex.main = 1.5, cex.lab = 1.5, bty = "o")

xlab <- paste("PC",as.numeric(1), " scores", sep="")
ylab <- paste("PC",as.numeric(2), " scores", sep="")
xMin <- min(rgSet@pca_m$scores[,as.numeric(1)])
xMax <- max(rgSet@pca_m$scores[,as.numeric(2)])
xRange <- xMax - xMin
xlim <- c(xMin-0.05*xRange, xMax+0.20*xRange)

plot(rgSet@pca_m$scores[,1], rgSet@pca_m$scores[,2],
         col = sampleColorsPCA(), pch = 19, cex = 2, xlab = xlab,
         ylab = ylab, xlim = xlim,
         main = "M-values (PCA)",
         cex.main = 1.5, cex.lab = 1.5, bty = "o")
```
```{r}
```

